version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: wiseup_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: